POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYTEyMyIsImlkIjoiNWVmMGZjMjA3Yjg0OTcxZWE0YjFlYmQ1IiwiaWF0IjoxNTkyODUxNTIzfQ.H9553-iS4KbmxCzWMXMdembBaI0VrUOcx-bF1GbYaz0

{
    "title": "maramrarj",
    "author": "jarpo",
    "url": "f4.com",
    "likes": 766
}