POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYSIsImlkIjoiNWVmMGUzMTQyZTAzMGExYzhjMmM1NGIzIiwiaWF0IjoxNTkyODQ1MTA4fQ.nL81ENh4RxfQNBi8md-9xUpGFtJdBg7_wJyivBemRzw

{
    "title": "argfgfgdf",
    "author": "jarpo",
    "url": "f234234234234.com",
    "likes": 777
}